#!/usr/bin/env php
<?php

require __DIR__ . "/vendor/autoload.php";

// Get rid of the first './primi' script argument.
array_shift($argv);

$cli = new \Smuuf\Primi\Cli\Entrypoint($argv, __DIR__);
$cli->execute();

