#!/usr/bin/env php
<?php

// Composer's autoload.
require __DIR__ . "/vendor/autoload.php";

// Autoloader.
$loader = new \Smuuf\Koloader\Autoloader(__DIR__ . "/temp/");
$loader->addDirectory(__DIR__ . "/src")->register();

array_shift($argv);
if (empty($argv[0])) {
	die_with_help();
}

$config = parse_arguments($argv);

if ($config['input_is_code']) {
	$source = $config['input'];
} else {
	$filepath = $config['input'];
	if (!is_file($filepath)) {
		die("Input file '$filepath' not found.\n");
	}
	$source = file_get_contents($filepath);
}

// Load source, create "VM" context and create the interpreter.

$context = new \Smuuf\Primi\Context;
$interpreter = new \Smuuf\Primi\Interpreter($context, __DIR__ . "/temp/");

try {

	// Get syntax tree.
	if ($config['tree']) {
		print_r($interpreter->getSyntaxTree($source));
		die;
	}

	// Run interpreter
	$interpreter->run($source);
	if ($config['print_context']) {
		print_r($context->getVariables());
		die;
	}

} catch (\Smuuf\Primi\ErrorException $e) {

	die($e->getMessage() . "\n");

}

function parse_arguments(array $args): array {

	$config = [
		'tree' => false,
		'print_context' => false,
		'input_is_code' => false,
		'input' => false,
	];

	while ($a = array_shift($args)) {
		switch ($a) {
			case "-t":
			case "--tree":
				$config['tree'] = true;
			break;
			case "-s":
			case "--source":
				$config['input_is_code'] = true;
			break;
			case "-c":
			case "--print-context":
				$config['print_context'] = true;
			break;
			default:
				$config['input'] = $a;
			break;
		}
	}

	return $config;

}

function die_with_help() {

	$help = <<<HELP
Primi language (CLI), Copyright (c) Premysl Karbula
Usage: primi <options> <input>
Options:
  -t, --tree     Only print syntax tree and exit.
  -s, --source   Treat <input> as string instead of a source file path.
  -c, --context  Print contents of primary context after execution.

HELP;

	die($help);

}
